name: jotform
description: Jotform API
version: 1.0.5
repository: https://github.com/ArcaneArts/jotform
environment:
  sdk: ^3.5.2
dependencies:
  dart_mappable: ^4.3.0
  http: ^1.2.2
  toxic: ^1.3.2
dev_dependencies:
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.3.0
scripts: 
  build_runner: dart pub run build_runner build --delete-conflicting-outputs